plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
    namespace "net.openconnect_vpn.android"
    defaultConfig {
        applicationIdSuffix ".firetv"
        minSdk 23
        targetSdk 34
        compileSdk 35

        versionCode 1121
        versionName "1.12"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    if (file("release.properties").exists()) {
        signingConfigs {
            release {
                file("release.properties").with {
                    def properties = new Properties()
                    properties.load(new FileInputStream(it))

                    storeFile file(properties['path'])
                    keyAlias properties['alias']
                    storePassword properties['password']
                    keyPassword properties['password']
                }
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (file("release.properties").exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
    lintOptions {
        disable 'ExtraTranslation'
        disable 'IconColors'
        disable 'InconsistentArrays'
        disable 'MissingTranslation'
        disable 'OldTargetApi'
        disable 'SuspiciousIndentation'

        // It's a tremendous amount of work to get rid of all references to `Context` in the app
        disable 'StaticFieldLeak'

        baseline file("lint-baseline.xml")
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
    buildFeatures {
        aidl true
        compose true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation platform('androidx.compose:compose-bom:2025.01.00')
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.runtime:runtime'
    implementation 'androidx.activity:activity-compose'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose'
    implementation 'androidx.tv:tv-material:1.0.0'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0'

    debugImplementation 'androidx.compose.ui:ui-tooling'

    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.1'
}
